### ISSUE TITLE
JDBC 9.2 fails to connect to Azure Data Explorer by ActiveDirectoryPassword

### ISSUE THREAD

**Issue by j2-z** [microsoft/mssql-jdbc#1525]
## Driver version
9.2.0-jre8

## SQL Server version
(Connect to Azure Data Explorer)

## Client Operating System
Windows 10

## JAVA/JVM version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

## Table schema
N/A - not related to the issue

## Problem description
We are using MSSQL JDBC to connect to ADX (Azure Data Explorer) by ActiveDirectoryPassword. It works before by using JDBC 8.4.0+ADAL4J lib. Now JDBC 9.2.0 switches to use MSAL4J lib. But when we try to use JDBC 9.2.0 + MSAL4J lib to connect to ADX by ActiveDirectoryPassword by using the same connection properties, it fails to connect now.

https://docs.microsoft.com/en-us/azure/data-explorer/kusto/api/tds/aad#jdbc-user 

## JDBC trace logs
```
com.microsoft.sqlserver.jdbc.SQLServerException: Failed to authenticate the user *****@*****.com in Active Directory (Authentication=ActiveDirectoryPassword).
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:227)
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getSqlFedAuthToken(SQLServerMSAL4JUtils.java:65)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:4524)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:4497)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:4460)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:289)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:125)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5332)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4068)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:85)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4006)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3274)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2768)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2265)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1291)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:881)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at jdbctest.AdxJdbc.main(AdxJdbc.java:27)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: AADSTS9001023: The grant type is not supported over the /common or /consumers endpoints. Please use the /organizations or tenant-specific endpoint.
Trace ID: 36c42731-f7bb-4a18-bf80-f143241d3900
Correlation ID: 782a20a2-d5ba-49cb-b563-2896fd42ad4f
Timestamp: 2021-03-01 06:22:32Z
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:225)
	... 21 more
Caused by: java.lang.RuntimeException: AADSTS9001023: The grant type is not supported over the /common or /consumers endpoints. Please use the /organizations or tenant-specific endpoint.
Trace ID: 36c42731-f7bb-4a18-bf80-f143241d3900
Correlation ID: 782a20a2-d5ba-49cb-b563-2896fd42ad4f
Timestamp: 2021-03-01 06:22:32Z
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:219)
	... 21 more
```

## Reproduction code
```java
package jdbctest;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

public class AdxJdbc {

    public static void main(String[] args) throws SQLException {
        String url = "jdbc:sqlserver://*****.eastus.kusto.windows.net:1433;databaseName=*****";

        Properties props = new Properties();
        props.put("user", "*****@*****.com");
        props.put("password", "*****");
        props.put("authentication", "ActiveDirectoryPassword");    
        props.put("hostNameInCertificate", "*.kusto.windows.net");  
        props.put("encrypt", "true");

        try (Connection connection = DriverManager.getConnection(url, props)) {
            System.out.println("Connected sucessfully!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
```
POM file:
```pom
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>test</groupId>
  <artifactId>jdbc-adx</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <dependencies>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>9.2.0.jre8</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>msal4j</artifactId>
      <version>1.9.1</version>
    </dependency>
  </dependencies>
</project>
```

If we use MSSQL JDBC 8.4.0 with ADAL4J, then the above Java code can connect to the ADX successfully.
```pom
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>test</groupId>
  <artifactId>jdbc-adal4j-adx</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <dependencies>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>8.4.0.jre8</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>adal4j</artifactId>
      <version>1.6.6</version>
    </dependency>
  </dependencies>
</project>
```

**Comment by peterbae** [comment]
Hi @j2-z, thanks for letting us know. We don't test on Azure Data Explorer officially, but we will look into this issue. However, it will be on a lower priority for now, until we can get an environment that we can test against.

**Comment by j2-z** [comment]
> Hi @j2-z, thanks for letting us know. We don't test on Azure Data Explorer officially, but we will look into this issue. However, it will be on a lower priority for now, until we can get an environment that we can test against.

Thanks for your reply! Looking forward to your update.

**Comment by lilgreenbird** [comment]
linking to AzureAD/microsoft-authentication-library-for-java/issues/382

**Comment by v-zhangw** [comment]
This issue was resolved in an email chain.
For reference, this behaviour is due to a change in the scope of what MSAL authenticates with a common authority compared to ADAL. More here: https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Migrate-to-MSAL-Java

**Comment by j2-z** [comment]
> This issue was resolved in an email chain.
> For reference, this behaviour is due to a change in the scope of what MSAL authenticates with a common authority compared to ADAL. More here: https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Migrate-to-MSAL-Java

Could I know how can I solve the issue if we are using JDBC? It's not clear to me how to solve it by using JDBC. We are not using MSAL lib directly, it's the JDBC code who acquires tokens. Does the latest JDBC fix it?

**Comment by lilgreenbird** [comment]
apologies this should not have been closed, it is still not resolved

**Comment by cheenamalhotra** [comment]
@j2-z 

This issue is not related to JDBC Driver, but underlying MSAL4J library that the driver depends on.
see: https://github.com/Azure/azure-sdk-for-java/issues/23146 and https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/382 (I've requested to reopen this) for more details.

This issue cannot be fixed by us, but only by MSAL4J Team. MSAL.NET works completely fine, SSMS/Azure Data Studio work, interactive authentication in Java works fine with "/common", problem is only in username/password authentication with MSAL4J.

Please follow-up with them on linked issues.

**Comment by v-zhangw** [comment]
As we do not control either the endpoints from ADX or how/what is accepted by MSAL, I cannot see what the JDBC driver can do to address this issue. It appears from the documentation and discussion on the MSAL github and related issue https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/382 that this behavior is by design and unlikely to change.

**Comment by j2-z** [comment]
I noticed that when MSSQL JDBC connects to an ADX server, the STSURL it received is `https://login.microsoftonline.com/common`
I wonder if it returns `https://login.microsoftonline.com/{tenantID}` then it might be able to work.
Is there any way to configure in ADX or Azure side to make ADX returns `https://login.microsoftonline.com/{tenantID} as STSURL ? `
```
Aug 18, 2021 4:06:40 PM com.microsoft.sqlserver.jdbc.SQLServerConnection processFedAuthInfo
FINE: ConnectionID:1 ClientConnectionId: xxxxx FedAuthInfoData: https://xxx.eastus.kusto.windows.net/
Aug 18, 2021 4:06:40 PM com.microsoft.sqlserver.jdbc.SQLServerConnection processFedAuthInfo
FINE: ConnectionID:1 ClientConnectionId: xxxxx FedAuthInfoOpt: ID=1, DataLen=80, Offset=104
Aug 18, 2021 4:06:40 PM com.microsoft.sqlserver.jdbc.SQLServerConnection processFedAuthInfo
FINE: ConnectionID:1 ClientConnectionId: xxxxx FedAuthInfoData: https://login.microsoftonline.com/common
```

**Comment by yogilad** [comment]
Hi,

We recently added a workaround to control the authority to authenticate to.
You can change authority , via SQL connection string _Language_ or _application_ fields (depends where and how each available on specific client – ADO.NET, ODBC, JDBC, etc.), for example:
```
Language=English@AadAuthority:YYYY
application=myappname@AadAuthority:YYYY
```

You can attempt this with the `organizations` keyword or with your specific tenant Id, and see if it helps.
If it does the change can later be applied as a default on the cluster.

**Comment by venkis81** [comment]
@j2-z  I am using one standalone java file and trying to use AD authentication with password and facing the same issue. In that case how do we set  props.put("applicationName", "myappname@AadAuthority:organizations");
