### ISSUE TITLE
useBulkCopyForBatchInsert does not work / output

### ISSUE THREAD

**Issue by JDBC-0** [microsoft/mssql-jdbc#2527]
## Driver version
12.8.1

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU28-GDR) (KB5042749) - 15.0.4390.2 (X64)   Aug 12 2024 13:08:42   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

## Client Operating System
Windows 10 Pro

## JAVA/JVM version
21.0.4

## Problem description
After we adjusted some tables from DATETIME to DATETIME2, changed all our prepared stored procedures to prepared INSERT statements, following all restrictions in "Known limitations" (https://learn.microsoft.com/en-us/sql/connect/jdbc/use-bulk-copy-api-batch-insert-operation?view=sql-server-ver16#known-limitations) and switching URL parameter "useBulkCopyForBatchInsert" between true and false, we don't see any effect of this parameter!

## Expected behavior
Batch INSERTs are faster with useBulkCopyForBatchInsert=true or info/warning message is logged if driver falls back to default batch INSERTs. As "Known Limitations" saiys:

"**If the query fails because of errors unrelated to the SQL Server instance, the driver **logs the error message** and falls back to the original logic for batch insert.**"

## Actual behavior
Nothing - performance is identical and our app logs don't show any log entry that the driver is falling back to standard batch INSERTs when useBulkCopyForBatchInsert=true is set but can't be used.

## Any other details that can be helpful
JDBC URL:  jdbc:sqlserver://{DBSERVERADR};databaseName=amc;applicationName=amcAppServer-{HOSTID};workstationID={HOSTID};integratedSecurity=true;sendStringParametersAsUnicode=false;encrypt=false;useBulkCopyForBatchInsert=true;sendTemporalDataTypesAsStringForBulkCopy=false

**Comment by JDBC-0** [comment]
Well, some progress:  I noticed a DATETIME column that I also replaced by DATETIME2. Then I get:

"Error save PosDetM (3001): Massenladedaten wurden erwartet, aber nicht gesendet. Der Batch wird beendet."

So, this is the first sign that "something" is happening with useBulkCopyForBatchInsert=true ... no idea what the problem is because the code is as expected: addBatch() ... executeBatch() ... ?

**Comment by lilgreenbird** [comment]
this looks to be a duplicate of #1784 which is still under investigation. Please limit all correspondence to that issue to avoid any duplication.

**Comment by JDBC-0** [comment]
@lilgreenbird : it's not the same:  #1784 is a special case with sendStringParametersAsUnicode .... this ticket here #2527 is a general ticket about bulk copy:  how to detect what the driver is doing? We don't see any log output if the driver somehow decides not to use bulk copy feature.

It would be helpful to have at least a warning log entry why it is not used. And if it is used, an info log message would also be helpful to indicate that bulk copy feature is actually used.

**Comment by JDBC-0** [comment]
Is there any kind of documentation how to get this working? We set ab our tables and replaced DATE/DATETIME with DATETIME2 because this is probably a requirement for bulk insert to work.  What URL Parameters are required with what value? And what URL Parameters do hurt/deactivate bulk insert? How can we output/log/inspect if the driver is actually using bulk insert?

**Comment by JDBC-0** [comment]
I tested the bulk insert feature again with additional URL parameters:

...;integratedSecurity=true;encrypt=false;sendStringParametersAsUnicode=false;useBulkCopyForBatchInsert=true;sendTemporalDataTypesAsStringForBulkCopy=false;cacheBulkCopyMetadata=true

and get this error again:

com.microsoft.sqlserver.jdbc.SQLServerException: Massenladedaten wurden erwartet, aber nicht gesendet. Der Batch wird beendet. at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:270) at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1735) at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatementBatch(SQLServerPreparedStatement.java:3025) at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtBatchExecCmd.doExecute(SQLServerPreparedStatement.java:2873) at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7745) at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4391) at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:276) at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:246) at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2264)

Error message translated: "Bulk load data was expected but not sent. The batch will be terminated.". Changing ;sendStringParametersAsUnicode=true didn't help (and we wouldn't want this anyway).

We changed out table columns (for a specific task) to replace DATE/DATETIME with DATETIME2 and user batch INSERT statements.

This was tested with driver 12.8.1 ... but tests with latest 12.10.0 shows the same error.

Info: our application connects to a database "dbA", calls procedurs from this database "A" but the destination tables the mass data is stored to is in database "dbB", so, our prepared statement looks like

INSERT INTO dbB.dbo.MyTable VALUES (?,?,?,...)

Might this be a problem?

**Comment by JDBC-0** [comment]
I was happy to read in 13.1.0:

> Support for temporal and money datatypes when using bulk copy for batch insert operations https://github.com/microsoft/mssql-jdbc/pull/2670
> What was added: Support for batch inserts of DATETIME, DATE, MONEY, etc., when using the useBulkCopyForBatchInsert option.

So I testet 13.1.1 pre-release: the result: it is even SLOWER with the new driver compared to the old driver (12.10.0)!

Our JDBC params:

...integratedSecurity=true;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=false;useBulkCopyForBatchInsert=true;sendTemporalDataTypesAsStringForBulkCopy=false;cacheBulkCopyMetadata=true

We don't see any indication / log output if bulk insert was used, so we can't tell if bulk copy is really active.

As it is  slower than 12.10.0, I fear this prerelease is not optimzed and with debug code?

And still the same question: if there is no noticable increase of INSERT speed, how can we check if the enabled bulk copy feature was really used?

BTW: we call JDBC addBatch() up to 4999 statements , then commit(), clearVatch(), next 4999 statements.

Config:
Java: OpenJDK  21 LTS
SQL Server: Microsoft SQL Server 2019 (RTM-CU32-GDR) (KB5058722) - 15.0.4435.7 (X64)   Jun  9 2025 18:36:12   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by David-Engel** [comment]
The driver outputs FINE logs when falling back to batch inserts:
https://github.com/microsoft/mssql-jdbc/blob/main/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java#L2311

```
                    getStatementLogger().fine("Parsing user's Batch Insert SQL Query failed: " + e.getMessage());
                    getStatementLogger().fine("Falling back to the original implementation for Batch Insert.");
```

**Comment by JDBC-0** [comment]
Just tested 13.2.1 ... no progress: it'*s still much slower with useBulkCopyForBatchInsert enabled:

useBulkCopyForBatchInsert=false => 11 min
useBulkCopyForBatchInsert=true => 15 min

Again: with sendStringParametersAsUnicode=false set as we need this.

**Comment by machavan** [comment]
This issue was addressed in 13.2 GA.

**Comment by JDBC-0** [comment]
Any progress? We updated to V 13.4.0 and still see no performance increase.

Is there any recommendation for the INSERT batches? E.g. what batch size to use and when to commit? So far, we do

   PreparedStatement.addBatch(); //INSERT INTO table1 (Column1, ...) VALUES (?,...)

up to 4999 rows. Then we we do

  executeBatch()
  commit()
 clearBatch()

and continue with the next 4999 rows .... it's unclear if the batch size can be increased to avoid table locks and/or the commit can be extended: e.g. executeBatch() after 4999 rows but commit after 20.000 rows .... and what this could mean concerning SQL table locking and/or driver bulk feature?

Test with FINE Levele: no message "Batch Insert SQL Query failed" found => we can just assume that the driver is using bulk copy?

Our URL parameters:

;integratedSecurity=true;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=false;useBulkCopyForBatchInsert=true;cacheBulkCopyMetadata=true;sendTemporalDataTypesAsStringForBulkCopy=false

@machavan

**Comment by JDBC-0** [comment]
And again an error with V 13.4.0:

"Bulk load failed due to schema change of the target table."

Error rating '98469': Fehler bei Masseneinfügung aufgrund einer Schemaänderung der Zieltabelle. errorCode=0, message=Fehler bei Masseneinfügung aufgrund einer Schemaänderung der Zieltabelle., SQLState=null, cause=null
java.sql.BatchUpdateException: Fehler bei Masseneinfügung aufgrund einer Schemaänderung der Zieltabelle.
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2475)
at de.icomps.sql.JDBC.executeBatch(Unknown Source)

**Comment by muskan124947** [comment]
Hi @JDBC-0 

We’ve already closed multiple issues related to bulk copy, including:

- Performance fixes when sendStringParametersAsUnicode=true/false
- Datetime support issues

Could you please open a new GitHub issue with complete details and a repro sample? That will help us track and investigate this specific problem properly.

**Comment by JDBC-0** [comment]
@muskan124947 I opened THIS issue for this general problem as the previous tickets were also closed without resolving our problem. I can't offer a reproducable case because it's much too big. I repeat what I have written earlier / in the other issues:

We had to disable bulk copy especially for 1 process - alle other processes seem to work with bulk copy but we have no idea if it's working or falling back (so no benefit from enabling it - but also no exception).

The one process that throws these errors is quite big and complex. Compared to all other processes (without these exceptions) it has:

* multiple concurrent threads, each deleting and inserting rows from a (different) table.
* 2 of those tables have partitioning

The concurrent threads shouldn't be a problem, as each thread only works on its own destination table.
The partitioning of 2 of those tables might be a problem (or the cause) but this exception doesn't tell.
